# MySql + phpmyadmin

version: '3.1'

services:

  #MySql
  db:
    image: mysql
    container_name: CSS326mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CSS326
    networks:
      - dev_network

  #php
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: CSS326
    networks:
      - dev_network


networks:
  dev_network:

volumes:
  db_data: